require:
  - standard
  - rubocop-performance
  - rubocop-minitest

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - dev_tools/**/*
    - .*/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - storage/**/*
    - vendor/**/*
