name: Rubocop

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: really_development

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Rubocop inspection
      run: bundle exec rake rubocop
